//from uri in sdm-key
@cmisuri = https://api-sdm-di.cfapps.eu10.hana.ondemand.com

//from uaa/clientid in sdm-key
@cmisclientid = sb-4fae8921-d66e-4624-ab25-640c682bee76!b149617|sdm-di-SDM_DI_PROD-prod!b41064
//from uaa/clientsecret in sdm-key
@cmisclientsecret = 137faac1-3320-47f1-9c84-10195bae7b48$BqSdXNqLl23IdkgVveeiy5SvB9UXab8xrNoNz4_4iu8=
//from uaa/url in sdm-key
@cmistokenurl = https://apjextabapsubdomain.authentication.eu10.hana.ondemand.com


# @name getToken
POST {{cmistokenurl}}/oauth/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Authorization: Basic {{cmisclientid}}:{{cmisclientsecret}}

client_id={{cmisclientid}}
&grant_type=client_credentials

###

# @name createRepository
@authToken = {{getToken.response.body.access_token}}
POST {{cmisuri}}/rest/v2/repositories HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{authToken}}

	{
		"repository": {
			"displayName": "freightorderattach",
			"description": "freightorderattach",
			"repositoryType": "internal",
			"isVersionEnabled":"false",
			"isVirusScanEnabled":"false",
			"skipVirusScanForLargeFile": "false",
			"isThumbnailEnabled": "false",
			"isEncryptionEnabled": "false",
			"isClientCacheEnabled": "false",
			"hashAlgorithms":"SHA-256",
			"isContentBridgeEnabled" : "false" 
			}
	}



###

# @name getRepository
@authToken = {{getToken.response.body.access_token}}
GET {{cmisuri}}/browser HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{authToken}}



###

# @name delRepository
@authToken = {{getToken.response.body.access_token}}
DELETE  {{cmisuri}}/browser/zfoattachment008 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{authToken}}











